"""
generators/combinational_vhdl.py
Generates VHDL-2008 from a TruthTableModel + SignalModel.

Architecture:
  - entity with port map (std_logic / std_logic_vector)
  - architecture with one concurrent when-else per output bit
  - Don't-care inputs (X) → that bit/signal omitted from the condition
  - Bus inputs  → std_logic_vector slice in condition
  - Bus outputs → individual bit when-elses assembled into a concatenation
"""


from models.signal_model import SignalModel, Signal, Direction
from models.truth_table_model import TruthTableModel


# ── helpers ────────────────────────────────────────────────────────────── #

def _vhdl_type(sig: Signal) -> str:
    if sig.width == 1:
        return "std_logic"
    return f"std_logic_vector({sig.width - 1} downto 0)"


def _port_lines(signal_model: SignalModel) -> list[str]:
    lines = []
    sigs  = signal_model.all_signals()
    for i, sig in enumerate(sigs):
        sep = ";" if i < len(sigs) - 1 else ""
        lines.append(
            f"        {sig.name:<16}: {sig.direction.value:<4} "
            f"{_vhdl_type(sig)}{sep}"
        )
    return lines


def _bus_terms(sig_name: str, sig_cols: list[dict],
               sig_vals: list[str]) -> list[str]:
    """
    Build VHDL condition terms for one bus signal (width > 1)
    when some bits are X (don't care).

    Finds runs of consecutive known (non-X) bits and emits:
      - single known bit  → sig(n) = '0' / '1'
      - run of known bits → sig(hi downto lo) = "0101"
    """
    terms = []
    n = len(sig_cols)
    run_start = None
    for k in range(n + 1):              # +1 to flush the last run
        val = sig_vals[k] if k < n else "X"   # sentinel
        if val != "X":
            if run_start is None:
                run_start = k
        else:
            if run_start is not None:
                run_cols = sig_cols[run_start:k]
                run_vals = sig_vals[run_start:k]
                hi_bit   = run_cols[0]["bit"]
                lo_bit   = run_cols[-1]["bit"]
                if len(run_cols) == 1:
                    terms.append(
                        f"{sig_name}({hi_bit}) = '{run_vals[0]}'"
                    )
                else:
                    literal = "".join(run_vals)
                    terms.append(
                        f'{sig_name}({hi_bit} downto {lo_bit}) = "{literal}"'
                    )
                run_start = None
    return terms


def _condition_for_row(input_cols: list[dict], row_data: list[str]) -> str:
    """
    Build the full VHDL condition string for one truth-table row.

    Scalars (width=1):
        known → sig = '0' / '1'    |   X → omitted
    Buses (width>1):
        all known → sig = "0101"
        some X    → per-run slices: sig(3 downto 2) = "01" and ...
        all X     → omitted entirely

    Returns None when every input is X (unconditional / catch-all row).
    """
    terms = []
    n_in  = len(input_cols)
    i = 0
    while i < n_in:
        sig = input_cols[i]["signal"]
        j = i
        while j < n_in and input_cols[j]["signal"] is sig:
            j += 1
        sig_cols = input_cols[i:j]
        sig_vals = [row_data[c["col_idx"]] for c in sig_cols]

        if sig.width == 1:
            if sig_vals[0] != "X":
                terms.append(f"{sig.name} = '{sig_vals[0]}'")
        else:
            if "X" not in sig_vals:
                literal = "".join(sig_vals)
                terms.append(f'{sig.name} = "{literal}"')
            else:
                terms.extend(_bus_terms(sig.name, sig_cols, sig_vals))
        i = j

    return " and ".join(terms) if terms else None


def _output_default(sig: Signal) -> str:
    if sig.width == 1:
        return "'0'"
    return f"(others => '0')"


# ── main generator ─────────────────────────────────────────────────────── #

class CombinationalVHDLGenerator:

    def generate(self, entity_name: str,
                 arch_name: str,
                 signal_model: SignalModel,
                 tt_model: TruthTableModel,
                 dc_value: str = "-") -> str:
        """
        dc_value controls what VHDL value is emitted for output cells marked X:
            '-'  → std_logic don't care (synthesiser optimises freely)
            '1'  → cover the minterm
            '0'  → don't cover (skip the row entirely)
        """

        if not entity_name.strip():
            entity_name = "combinational"
        if not arch_name.strip():
            arch_name = "rtl"

        lines = []

        # ── header ──
        lines += [
            "-- Auto-generated by VHDL Design Tool",
            "-- VHDL-2008  |  Combinational design",
            "",
            "library ieee;",
            "use ieee.std_logic_1164.all;",
            "",
        ]

        # ── entity ──
        port_lines = _port_lines(signal_model)
        lines += [
            f"entity {entity_name} is",
            "    port (",
        ]
        lines += port_lines
        lines += [
            "    );",
            f"end entity {entity_name};",
            "",
        ]

        # ── architecture ──
        lines += [
            f"architecture {arch_name} of {entity_name} is",
            "begin",
            "",
        ]

        input_cols  = tt_model.input_columns()
        output_cols = tt_model.output_columns()
        n_rows      = tt_model.rowCount()

        # One when-else block per output bit-column
        for out_col in output_cols:
            sig     = out_col["signal"]
            bit     = out_col["bit"]        # None for scalar
            col_idx = out_col["col_idx"]

            # lhs of the assignment
            if sig.width == 1:
                lhs = sig.name
            else:
                lhs = f"{sig.name}({bit})"

            # build when-else chain — one branch per '1' or X row
            # (X handling controlled by dc_value parameter)
            assign_lines = [f"    {lhs} <="]

            any_branch = False
            for r in range(n_rows):
                row_data = tt_model.row_data(r)
                out_val  = row_data[col_idx]

                # Determine what VHDL value to emit for this cell
                if out_val == "1":
                    out_vhdl = "'1'"
                elif out_val == "X":
                    if dc_value == "0":
                        continue        # skip — treat as don't cover
                    out_vhdl = f"'{dc_value}'"  # '-' or '1'
                else:
                    continue            # '0' rows never generate a branch

                cond = _condition_for_row(input_cols, row_data)

                if cond is None:
                    # unconditional assignment — use as final else
                    assign_lines.append(f"        {out_vhdl}")
                    any_branch = True
                    break
                else:
                    assign_lines.append(
                        f"        {out_vhdl} when {cond} else"
                    )
                    any_branch = True

            if any_branch:
                # check if last line already has no "else" (unconditional)
                if assign_lines[-1].rstrip().endswith("else"):
                    assign_lines.append(
                        f"        {_output_default(sig)};"
                    )
                else:
                    # last line is unconditional value, add semicolon
                    assign_lines[-1] = assign_lines[-1].rstrip() + ";"
            else:
                # no '1' or 'X' found → output is always '0'
                assign_lines = [
                    f"    {lhs} <= {_output_default(sig)};"
                ]

            lines += assign_lines
            lines.append("")

        lines += [
            f"end architecture {arch_name};",
        ]

        return "\n".join(lines)
